# docker-compose.yml
version: "2.3"
services:

  api:
    build: ./cursodocker-api
    scale: 3
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3333-3339:3333"

  front:
    build: ./cursodocker-front
    restart: always
    depends_on:
      - api
    ports:
      - "8080:80"

  postgres:
    image: postgres:10.4
    restart: always
    volumes:
      - ~/docker-volumes/cursodocker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U cursodocker"]
      interval: 50s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cursodocker
